function R(items,o){const rc=Object.assign({items:items.map(([id,dose])=>({id,dose})),solvent:null,adj:null,tech:'infuser',feu:1,fin:{}},o);const r=prepare(rc);
 if(r.error)return console.log('ERR',r.error);
 if(r.accident)return console.log('ACC',r.accident.title);
 console.log(`${r.name} [${r.type}${r.alt.length?' +'+r.alt:''}] ${r.form} Q${r.quality.score} ${r.danger.label} | ${r.fx.slice(0,4).map(e=>e.id+':'+e.raw).join(' ')} | ${r.sensory.aspect}; odeur ${r.sensory.smell}; goût ${r.sensory.taste} | ${r.shelf.label}`)}
R([['bourrache_noire',2],['mauve_grasse',2]],{solvent:'eau_pluie'});
R([['melisse_tourbieres',3]],{solvent:'eau_pluie'});
R([['melisse_tourbieres',3]],{solvent:'alcool',tech:'macerer'});
R([['melisse_tourbieres',2],['fleur_nuit',2]],{solvent:'alcool',tech:'macerer',adj:'miel'});
R([['mauve_grasse',2],['larme_pin',1],['vesse_loup',2]],{adj:'graisse_oie',tech:'petrir',feu:0});
R([['belle_ombre',3]],{solvent:'alcool',tech:'macerer'});
R([['belle_ombre',2],['herbe_veuve',2]],{solvent:'eau_pluie',tech:'decocter'});
R([['argent_vif',1],['soufre_jaune',1]],{tech:'broyer'});
R([['argent_vif',1]],{tech:'calciner'});
R([['vitriol_vert',1],['cornouille_amere',2]],{solvent:'eau_pluie',tech:'decocter'});
R([['ortie_rousse',3]],{solvent:'eau_pluie',tech:'infuser'});
R([['ortie_rousse',3]],{tech:'broyer'});
R([['encens_rocaille',2],['ambre_gris',1]],{tech:'fumiger',feu:0});
R([['soufre_jaune',3]],{tech:'fumiger',feu:2});
R([['sel_amertume',2],['pierre_lune',2]],{solvent:'eau_pluie'});
R([['pierre_lune',3],['charbon_saule',2]],{solvent:'eau_pluie',tech:'infuser'});
R([['sauge_fievre',3]],{solvent:'eau_distillee',tech:'distiller'});
R([['sang_bouleau',3]],{solvent:'eau_pluie',tech:'fermenter',adj:'miel'});
R([['fiel_sanglier',2]],{solvent:'lait_chaux',adj:'graisse_oie',tech:'petrir'});
R([['racine_amere',2],['chardon_lanterne',2]],{solvent:'alcool',tech:'macerer'});
R([['vitriol_vert',2]],{solvent:'vinaigre',tech:'decocter'});
R([['fleur_cuivre',2]],{solvent:'vinaigre',tech:'macerer'});
R([['alun_cristallin',2],['cornouille_amere',2]],{solvent:'eau_pluie',tech:'decocter'});
R([['sel_noir',2],['salpetre_gris',2]],{tech:'broyer'});
R([['poudre_eclat',1]],{tech:'broyer'});
R([['venin_vipere',1]],{solvent:'alcool',tech:'macerer'});
R([['venin_vipere',3]],{solvent:'alcool',tech:'macerer'});
R([['herbe_veuve',1],['sabline',1]],{tech:'infuser'});
R([['mauve_grasse',1]],{tech:'infuser',solvent:'eau_pluie'});
R([['lichen_roche',3],['racine_amere',2],['poudre_corne',1]],{tech:'decocter',solvent:'eau_pluie',adj:'miel'});
R([['herbe_veuve',1]],{tech:'distiller',solvent:'alcool',feu:2});
R([['a',1]].slice(0,0),{});
